package main

import (
	"log"
	"math"
	"time"

	"github.com/bpineau/pofo/cmd/internal/refgen"
	"github.com/bpineau/pofo/pkg/marketdata"
)

// The 3-month Treasury bill rate, the sixth series this command writes.
//
// TBILL-3M is FRED's TB3MS, the secondary-market 3-month bill rate the Federal
// Reserve publishes in H.15, monthly from 1934-01. It is carried EXACTLY as
// FRED prints it: same values, same labels, nothing mapped or rescaled. It
// extends ^IRX before Yahoo's quotes begin (simgen's longBack), so it is the
// dollar cash leg every financed or funded reconstruction reads before 1960
// (the catalog's cash, trend, cat-bond and crude-oil recipes among them), and
// the FIRE book's cash sleeve.
//
// It sits here rather than in a command of its own because it is the short
// end of the same curve and belongs to the same refresh; it is read from FRED
// rather than from DBnomics because FRED is the source the file has always
// named, and the refresh must reproduce the bundled history point for point.
//
// The file had no generator until 2026-09 and froze at 2026-05 with nobody
// noticing, which quietly held every cash leg after it at the last print.
const (
	outBill  = "TBILL-3M"
	billFRED = "TB3MS"

	// billStart is FRED's first month, and the bundle's.
	billStart = "1934-01-01"

	// billFloats is the Treasury-Federal Reserve Accord (1951-03), after which
	// the bill rate is a market rate. Before it the Fed pegged it, at 3/8 %
	// from 1942 to 1947 (sixty identical months in the source), so the
	// flat-run check starts here.
	billFloats = "1951-04-01"
	// billMaxRun is the longest run of identical months allowed after the
	// Accord. Measured: three (1963-11 to 1964-01, at 3.52), and the zero-rate
	// years of 2009-2015 never repeat a print more than three times either.
	billMaxRun = 6

	// billMaxAge bounds the age of the last label. TB3MS is dated the FIRST of
	// the month it averages and published in the first days of the next, so a
	// healthy file is 35 to 70 days behind its last label; 100 means the
	// source stopped.
	billMaxAge = 100

	// billRevisable is how many of the bundled file's last months may differ
	// from the refreshed source. None ever has; the slack is there so a
	// genuine revision of the latest print is reported rather than blocking a
	// refresh, while any older move stops it.
	billRevisable = 2
)

// billSource is the file's "# source:" header: what the series is and why its
// first-of-month labels are the right ones, which is the part a consumer needs.
const billSource = "FRED TB3MS (3-month T-bill secondary market, 1934->). RATE levels (percent), proxy behind ^IRX; " +
	"spliced as an isRate series. CADENCE: TB3MS is the month's AVERAGE of the daily rates, dated the first of the " +
	"month, and that is the right convention for the use it is put to: every consumer accrues it forward from its " +
	"label, so a cash position earns month M's average rate over month M, which is what a monthly roll pays. A rate " +
	"is not a price and there is no smoothed path to repair here. Regenerated by cmd/gen-tyield-refdata " +
	"(make tyield-refdata), which carries FRED's values and labels unchanged and refuses a refresh that does not " +
	"reproduce this file's history."

func billHeader() refgen.Header {
	return refgen.Header{ID: outBill, Name: "US 3-month Treasury bill rate (annualized percent, monthly)", Source: billSource}
}

// fetchBill downloads TB3MS, or stops the generator.
func fetchBill(base string) []marketdata.Point {
	pts, err := refgen.FRED(base, billFRED)
	if err != nil {
		log.Fatalf("%s: %v", outBill, err)
	}
	report(outBill, "%/yr", pts)
	return pts
}

// checkBill grades the bill rate before it may replace the bundled file.
//
// The checks, and why each is the one to make:
//
//   - The shape. One observation a month, on the first, from 1934-01, none
//     missing: the layout every consumer accrues forward from.
//   - The range. A bill rate is positive (the bundle's reader refuses a
//     non-positive value, and TB3MS's lowest print is 0.01) and has never
//     reached 20 % (16.30 in 1981-01).
//   - Three eras an outside reader knows: the 3/8 % wartime peg, the
//     double-digit rates of 1980-1981 and the zero-rate years after 2008. A
//     wrong column or a percent/fraction slip misses all three by a mile.
//   - No flat run after the Accord longer than the market ever made: the
//     signature of a frozen feed.
//   - Freshness: the reason this generator exists.
//   - The bundled history, reproduced point for point (refgen.SameHistory).
//     TB3MS is a market rate FRED does not revise, so anything that moves
//     means the source changed, and every cash leg with it.
func checkBill(pts []marketdata.Point, dir string) {
	if first := pts[0].Date.Format(time.DateOnly); first != billStart {
		fail("%s starts %s, want %s", outBill, first, billStart)
	}
	if err := refgen.MonthlyCadence(pts); err != nil {
		fail("%s: %v", outBill, err)
	}
	for _, p := range pts {
		if !(p.Close > 0 && p.Close < 20) {
			fail("%s: %.2f %%/yr on %s, outside (0, 20)", outBill, p.Close, p.Date.Format(time.DateOnly))
			break
		}
	}
	for _, e := range []struct {
		what     string
		from, to string
		lo, hi   float64
	}{
		{"the wartime peg", "1942-07-01", "1947-06-01", 0.35, 0.40},
		{"the Volcker years", "1980-01-01", "1981-12-01", 10, 16},
		{"the zero-rate years", "2009-01-01", "2015-11-01", 0, 0.3},
	} {
		var sum float64
		var n int
		for _, p := range pts {
			if d := p.Date.Format(time.DateOnly); d >= e.from && d <= e.to {
				sum += p.Close
				n++
			}
		}
		mean := sum / float64(max(n, 1))
		log.Printf("check %s %s: mean %.3f %%/yr over %d months", outBill, e.what, mean, n)
		if n == 0 || mean < e.lo || mean > e.hi {
			fail("%s over %s (%s..%s) averages %.3f %%/yr, outside %.2f..%.2f", outBill, e.what, e.from, e.to, mean, e.lo, e.hi)
		}
	}
	run, end := refgen.FlatRun(pts, mustDate(billFloats))
	log.Printf("check %s flat runs since %s: longest %d months (ending %s)", outBill, billFloats, run, end.Format("2006-01"))
	if run > billMaxRun {
		fail("%s repeats one value for %d months, a frozen feed rather than a market", outBill, run)
	}
	last := pts[len(pts)-1].Date
	age := math.Floor(time.Since(last).Hours() / 24)
	log.Printf("check %s freshness: last month %s (%.0f days old)", outBill, last.Format("2006-01"), age)
	if age > billMaxAge {
		fail("%s: the last month is %.0f days old, the source has stopped", outBill, age)
	}
	old, ok, err := marketdata.ReadSimdata(dir, outBill)
	switch {
	case err != nil:
		fail("%s: reading the bundled file: %v", outBill, err)
	case !ok:
		log.Printf("check %s history: no bundled file in %s to compare with", outBill, dir)
	default:
		msg, err := refgen.SameHistory(old.Points, pts, billRevisable)
		if err != nil {
			fail("%s does not reproduce the bundled history: %v", outBill, err)
		} else {
			log.Printf("check %s history: %s", outBill, msg)
		}
	}
}
