// Command gen-dbi-refdata rebuilds
// pkg/datasets/refdata/TREND-ALLSTYLES-DBI-USD.csv, the donor the iMGP DBi
// managed-futures family stands on before its own quotes begin.
//
// The series is the published net ALL-STYLES managed-futures composite
// (TREND-ALLSTYLES-NET-USD, regenerated by cmd/gen-sgtrend-refdata), half of it
// re-expressed through the ten futures contracts the replicating fund actually
// holds. Why that is a better donor than the composite alone, and what it was
// measured to buy, is in docs/trend-reconstruction-design.md; the engine and
// the instrument list are simgen.DBiReplication.
//
// It runs at data-generation time only (network); the pofo binary embeds the
// CSV and never fetches anything. Run it AFTER cmd/gen-sgtrend-refdata, whose
// composite it reads, and BEFORE "make simdata", whose DBi files splice it.
//
//	go run ./cmd/gen-dbi-refdata [-dry] [-out DIR]
//
// Every series it writes is validated first, and a failing gate refuses to
// write rather than shipping a degraded file: the composite must be fresh and
// long, the projection must track it at the level and the path, and the blend
// must sit between the two.
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"math"
	"os"
	"path/filepath"
	"time"

	"github.com/bpineau/pofo/pkg/datasets"
	"github.com/bpineau/pofo/pkg/marketdata"
	"github.com/bpineau/pofo/pkg/simgen"
)

const outID = simgen.DBiDonorID

// source is the provenance the CSV carries.
const source = "the net all-styles managed-futures composite (TREND-ALLSTYLES-NET-USD, the SG CTA Index, " +
	"see cmd/gen-sgtrend-refdata for its own provenance), half of it re-expressed through the ten futures " +
	"contracts the iMGP DBi Managed Futures Strategy ETF holds. The projection regresses the composite's " +
	"trailing 60 days of daily excess returns on those ten contracts' excess returns, refits weekly, discards " +
	"the intercept and holds the resulting portfolio funded at the T-bill rate: the fund's own published " +
	"process (60-day window on the target's performance, US-traded contracts only, no manager discretion) run " +
	"on the public index with public price series, never fitted to the fund. The ten contracts and their " +
	"proxies are listed in pkg/simgen/dbireplica.go, each given back its proxy's own ongoing charge because a " +
	"futures contract levies none. The shipped series is the equal-weight average of the composite's and the " +
	"projection's daily returns, which measures better against the fund than either side alone; it starts 60 " +
	"trading days after the composite, the regression's warm-up. Regenerate with cmd/gen-dbi-refdata."

func main() {
	dry := flag.Bool("dry", false, "validate and report without writing")
	out := flag.String("out", filepath.Join("pkg", "datasets", "refdata"), "output directory")
	flag.Parse()

	if err := run(*out, *dry); err != nil {
		log.Fatalf("gen-dbi-refdata: %v", err)
	}
}

func run(dir string, dry bool) error {
	ctx := context.Background()
	client := marketdata.NewClient(marketdata.DefaultCacheDir())
	f := simgen.WithRefData(datasets.Refdata(), simgen.WithContext(ctx, client))

	ref, err := f.Fetch("TREND-ALLSTYLES-NET-USD", simgen.ComponentsFrom)
	if err != nil {
		return fmt.Errorf("composite: %w", err)
	}
	proj, err := simgen.DBiProjection(f, simgen.ComponentsFrom)
	if err != nil {
		return fmt.Errorf("projection: %w", err)
	}
	blend, err := simgen.DBiReplication(f, simgen.ComponentsFrom)
	if err != nil {
		return fmt.Errorf("blend: %w", err)
	}
	log.Printf("composite  %5d days %s to %s, CAGR %.2f %%/yr, vol %.2f %%",
		len(ref.Points), day(ref.First().Date), day(last(ref).Date), 100*cagr(ref), 100*vol(ref))
	log.Printf("projection %5d days %s to %s, CAGR %.2f %%/yr, vol %.2f %%",
		len(proj.Points), day(proj.First().Date), day(last(proj).Date), 100*cagr(proj), 100*vol(proj))
	log.Printf("blend      %5d days %s to %s, CAGR %.2f %%/yr, vol %.2f %%",
		len(blend.Points), day(blend.First().Date), day(last(blend).Date), 100*cagr(blend), 100*vol(blend))

	if err := validate(ref, proj, blend); err != nil {
		return err
	}

	var b []byte
	b = append(b, []byte("# pofo simdata v1\n# id: "+outID+"\n")...)
	b = append(b, []byte("# name: net all-styles managed-futures composite, half projected on the replicating fund's ten futures (USD, daily)\n")...)
	b = append(b, []byte("# source: "+source+"\ndate,close\n")...)
	for _, p := range blend.Points {
		b = append(b, []byte(fmt.Sprintf("%s,%.6f\n", day(p.Date), p.Close))...)
	}
	if dry {
		log.Printf("dry run: %d bytes, %d points, final level %.2f", len(b), len(blend.Points), last(blend).Close)
		return nil
	}
	path := filepath.Join(dir, outID+".csv")
	if err := os.WriteFile(path, b, 0o644); err != nil {
		return err
	}
	log.Printf("wrote %s (%d points)", path, len(blend.Points))
	return nil
}

// validate refuses to ship a series that is stale, short, or no longer the
// object this file is supposed to hold. Each gate exists because its failure
// mode is silent: a degraded fetch, a frozen upstream dataflow and a regression
// that stopped fitting all produce a plausible-looking CSV.
func validate(ref, proj, blend *marketdata.Series) error {
	if n := len(blend.Points); n < 6000 {
		return fmt.Errorf("blend too short: %d days, want at least 6000", n)
	}
	if d := last(ref).Date.Sub(last(blend).Date); d > 7*24*time.Hour {
		return fmt.Errorf("blend ends %s, the composite ends %s: the projection stopped early",
			day(last(blend).Date), day(last(ref).Date))
	}
	if age := time.Since(last(blend).Date); age > 120*24*time.Hour {
		return fmt.Errorf("stalest day is %s (%.0f days old): refresh the composite first",
			day(last(blend).Date), age.Hours()/24)
	}
	if start := blend.First().Date; start.After(ref.First().Date.AddDate(0, 5, 0)) {
		return fmt.Errorf("blend starts %s, more than five months after the composite's %s",
			day(start), day(ref.First().Date))
	}

	// The projection is a portfolio of the composite's own exposures, so it has
	// to look like the composite: a similar volatility, a level within a point
	// or so a year, and months that move together.
	from, to := blend.First().Date, last(blend).Date
	if r := vol(proj) / volOver(ref, from, to); r < 0.6 || r > 1.4 {
		return fmt.Errorf("projection volatility is %.2f times the composite's: the regression is not tracking it", r)
	}
	if gap := cagr(proj) - cagrOver(ref, from, to); math.Abs(gap) > 0.02 {
		return fmt.Errorf("projection CAGR is %+.2f pts/yr off the composite's: the level is not credible", 100*gap)
	}
	if c := monthlyCorr(proj, ref, from, to); c < 0.55 {
		return fmt.Errorf("projection tracks the composite at only %.3f monthly", c)
	}
	// The blend is an average, so it must sit between its two sides everywhere
	// it can be checked, and stay close to the composite.
	if c := monthlyCorr(blend, ref, from, to); c < 0.85 {
		return fmt.Errorf("blend tracks the composite at only %.3f monthly", c)
	}
	if gap := cagr(blend) - cagrOver(ref, from, to); math.Abs(gap) > 0.01 {
		return fmt.Errorf("blend CAGR is %+.2f pts/yr off the composite's", 100*gap)
	}
	if flat := longestFlat(blend); flat > 10 {
		return fmt.Errorf("blend repeats the same level %d days running: a leg went stale", flat)
	}
	log.Printf("validated: blend vs composite %.3f monthly, %+.2f pts/yr, %.2f x volatility",
		monthlyCorr(blend, ref, from, to), 100*(cagr(blend)-cagrOver(ref, from, to)), vol(blend)/volOver(ref, from, to))
	return nil
}

func day(t time.Time) string { return t.Format("2006-01-02") }

func last(s *marketdata.Series) marketdata.Point { return s.Points[len(s.Points)-1] }

func cagr(s *marketdata.Series) float64 { return cagrOver(s, s.First().Date, last(s).Date) }

func cagrOver(s *marketdata.Series, from, to time.Time) float64 {
	a, _, okA := s.At(from)
	b, _, okB := s.At(to)
	years := to.Sub(from).Hours() / 24 / 365.25
	if !okA || !okB || a <= 0 || years <= 0 {
		return 0
	}
	return math.Pow(b/a, 1/years) - 1
}

func vol(s *marketdata.Series) float64 { return volOver(s, s.First().Date, last(s).Date) }

func volOver(s *marketdata.Series, from, to time.Time) float64 {
	var r []float64
	for i := 1; i < len(s.Points); i++ {
		if s.Points[i].Date.Before(from) || s.Points[i].Date.After(to) || s.Points[i-1].Close <= 0 {
			continue
		}
		r = append(r, s.Points[i].Close/s.Points[i-1].Close-1)
	}
	return stdev(r) * math.Sqrt(252)
}

// monthlyCorr correlates two series' month-end returns over a window.
func monthlyCorr(a, b *marketdata.Series, from, to time.Time) float64 {
	ma, mb := monthly(a, from, to), monthly(b, from, to)
	var xa, xb []float64
	for k, v := range ma {
		if w, ok := mb[k]; ok {
			xa = append(xa, v)
			xb = append(xb, w)
		}
	}
	return pearson(xa, xb)
}

func monthly(s *marketdata.Series, from, to time.Time) map[int]float64 {
	ends := map[int]marketdata.Point{}
	for _, p := range s.Points {
		if p.Date.Before(from) || p.Date.After(to) || p.Close <= 0 {
			continue
		}
		k := p.Date.Year()*12 + int(p.Date.Month())
		if cur, ok := ends[k]; !ok || p.Date.After(cur.Date) {
			ends[k] = p
		}
	}
	out := map[int]float64{}
	for k, p := range ends {
		if prev, ok := ends[k-1]; ok && prev.Close > 0 {
			out[k] = p.Close/prev.Close - 1
		}
	}
	return out
}

func pearson(a, b []float64) float64 {
	if len(a) < 3 {
		return 0
	}
	var ma, mb float64
	for i := range a {
		ma += a[i]
		mb += b[i]
	}
	ma /= float64(len(a))
	mb /= float64(len(b))
	var cov, va, vb float64
	for i := range a {
		da, db := a[i]-ma, b[i]-mb
		cov += da * db
		va += da * da
		vb += db * db
	}
	if va <= 0 || vb <= 0 {
		return 0
	}
	return cov / math.Sqrt(va*vb)
}

func stdev(xs []float64) float64 {
	if len(xs) < 2 {
		return 0
	}
	var m float64
	for _, x := range xs {
		m += x
	}
	m /= float64(len(xs))
	var s float64
	for _, x := range xs {
		s += (x - m) * (x - m)
	}
	return math.Sqrt(s / float64(len(xs)-1))
}

// longestFlat is the longest run of identical levels, the signature of a leg
// that stopped quoting while the rest of the book kept trading.
func longestFlat(s *marketdata.Series) int {
	best, run := 0, 0
	for i := 1; i < len(s.Points); i++ {
		if s.Points[i].Close == s.Points[i-1].Close {
			run++
			best = max(best, run)
			continue
		}
		run = 0
	}
	return best
}
