// Command gen-gold-refdata refreshes pkg/datasets/refdata/XAUUSD-LBMA.csv, the
// daily London gold price in US dollars since the two-tier market of 1968-04.
//
// The series is the LBMA's own record of the afternoon fix (the LBMA Gold Price
// PM since 2015), read from the association's freely published JSON history and
// carried EXACTLY as published: one point per fixing day, the USD column, no
// adjustment. It is the deep proxy behind gold futures and gold funds before
// their own quotes begin (simgen's longBack of GC=F, and the gold recipes), so
// a frozen file holds every gold backcast's tail at its last fix.
//
// The file had no generator until 2026-09 and was last refreshed by hand at
// 2026-07. Nothing is trusted for having downloaded: before anything is written
// the refresh must reproduce the bundled history point for point (the fix is a
// price, never revised, so anything older than the last few fixes moving means
// the source changed), stay inside a band no gold price has left, pass three
// eras an outside reader knows, carry no frozen run, and be fresh.
//
// Usage: gen-gold-refdata [-src URL] [-dir path] [-dry]
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"math"
	"path/filepath"
	"time"

	"github.com/bpineau/pofo/cmd/internal/refgen"
	"github.com/bpineau/pofo/pkg/marketdata"
)

const (
	defaultSrc = "https://prices.lbma.org.uk/json/gold_pm.json"
	outID      = "XAUUSD-LBMA"

	// firstFix is the first day of the free-market record, and the bundle's:
	// the London market reopened in 1968-04 after the gold pool collapsed.
	firstFix = "1968-04-01"

	// maxMove is the largest one-day move the fix may make. Measured, the
	// record's largest is 13.3 % (1980-01-03, the peak of the 1980 run); a
	// quarter in a day would be a misread column or a unit slip.
	maxMove = 0.25
	// floats is where the flat-run check starts: until the mid-1970s the fix
	// could sit on one value for days (six fixings in a row in 1969). Since
	// 1975 it never repeated more than three times.
	floats = "1975-01-01"
	maxRun = 5
	// maxAge bounds the age of the last fix in days: a fix is struck every
	// London business day, so ten days covers the longest holiday.
	maxAge = 10
	// revisable is how many of the bundled file's last fixes may differ from
	// the refreshed source without stopping it.
	revisable = 5
)

// source is the file's "# source:" header.
const source = "LBMA daily PM fix (USD), " + defaultSrc + " (freely published); modern floating era from " +
	"1968-04. Carried exactly as published. Regenerated by cmd/gen-gold-refdata (make gold-refdata), which " +
	"refuses a refresh that does not reproduce this file's history."

func main() {
	src := flag.String("src", defaultSrc, "LBMA gold PM JSON history")
	dir := flag.String("dir", "pkg/datasets/refdata", "output directory")
	dry := flag.Bool("dry", false, "download and validate, write nothing")
	flag.Parse()

	raw, err := refgen.Get(*src)
	if err != nil {
		log.Fatalf("download: %v", err)
	}
	pts, err := parse(raw)
	if err != nil {
		log.Fatalf("parse: %v", err)
	}
	log.Printf("%s: %d fixes, %s to %s", outID, len(pts),
		pts[0].Date.Format(time.DateOnly), pts[len(pts)-1].Date.Format(time.DateOnly))
	if err := check(pts, time.Now()); err != nil {
		log.Fatalf("refusing to write %s: %v", outID, err)
	}
	old, ok, err := marketdata.ReadSimdata(*dir, outID)
	switch {
	case err != nil:
		log.Fatalf("reading the bundled %s: %v", outID, err)
	case !ok:
		log.Printf("no bundled %s in %s to compare with", outID, *dir)
	default:
		msg, err := refgen.SameHistory(old.Points, pts, revisable)
		if err != nil {
			log.Fatalf("refusing to write %s: it does not reproduce the bundled history: %v", outID, err)
		}
		log.Printf("history: %s", msg)
	}
	if *dry {
		log.Printf("dry run: nothing written")
		return
	}
	h := refgen.Header{ID: outID, Name: "Gold spot (XAU/USD, London/LBMA PM fix, daily)", Source: source}
	if err := refgen.Write(*dir, h, pts); err != nil {
		log.Fatalf("write: %v", err)
	}
	log.Printf("wrote %s (%d fixes)", filepath.Join(*dir, outID+".csv"), len(pts))
}

// parse reads the LBMA history: an array of fixing days, each with its date
// and its prices in USD, GBP and EUR, in that order. A day without a USD price
// (the source carries a few) is skipped rather than guessed.
func parse(raw []byte) ([]marketdata.Point, error) {
	var days []struct {
		D string     `json:"d"`
		V []*float64 `json:"v"`
	}
	if err := json.Unmarshal(raw, &days); err != nil {
		return nil, err
	}
	var out []marketdata.Point
	for _, d := range days {
		if len(d.V) == 0 || d.V[0] == nil || *d.V[0] <= 0 {
			continue
		}
		t, err := time.Parse(time.DateOnly, d.D)
		if err != nil {
			return nil, fmt.Errorf("bad date %q", d.D)
		}
		if n := len(out); n > 0 && !t.After(out[n-1].Date) {
			return nil, fmt.Errorf("%s does not follow %s", d.D, out[n-1].Date.Format(time.DateOnly))
		}
		out = append(out, marketdata.Point{Date: t, Close: *d.V[0]})
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("no USD fix in the source")
	}
	return out, nil
}

// check grades the refreshed record on its own: where it starts, a price
// inside the band gold has kept since 1968, no one-day move beyond maxMove,
// three eras an outside reader knows (the late Bretton Woods years near the
// official 35 dollars, the 1980 bubble, the 2020 record), no frozen run since
// the fix became a free market, and a last fix no older than maxAge days.
func check(pts []marketdata.Point, now time.Time) error {
	if first := pts[0].Date.Format(time.DateOnly); first != firstFix {
		return fmt.Errorf("starts %s, want %s", first, firstFix)
	}
	for i, p := range pts {
		if !(p.Close > 30 && p.Close < 20000) {
			return fmt.Errorf("%.2f USD an ounce on %s, outside (30, 20000)", p.Close, p.Date.Format(time.DateOnly))
		}
		if i > 0 && math.Abs(p.Close/pts[i-1].Close-1) > maxMove {
			return fmt.Errorf("%+.1f %% on %s, beyond any day the fix has made", (p.Close/pts[i-1].Close-1)*100, p.Date.Format(time.DateOnly))
		}
	}
	for _, e := range []struct {
		what     string
		from, to string
		lo, hi   float64
	}{
		{"the late Bretton Woods years", "1968-04-01", "1970-12-31", 35, 43},
		{"1980", "1980-01-01", "1980-12-31", 550, 680},
		{"2020", "2020-01-01", "2020-12-31", 1650, 1900},
	} {
		var sum float64
		var n int
		for _, p := range pts {
			if d := p.Date.Format(time.DateOnly); d >= e.from && d <= e.to {
				sum += p.Close
				n++
			}
		}
		mean := sum / float64(max(n, 1))
		log.Printf("check %s: mean fix %.2f USD over %d days", e.what, mean, n)
		if n == 0 || mean < e.lo || mean > e.hi {
			return fmt.Errorf("%s (%s..%s) averages %.2f USD, outside %.0f..%.0f", e.what, e.from, e.to, mean, e.lo, e.hi)
		}
	}
	from, _ := time.Parse(time.DateOnly, floats)
	run, end := refgen.FlatRun(pts, from)
	log.Printf("check flat runs since %s: longest %d fixes (ending %s)", floats, run, end.Format(time.DateOnly))
	if run > maxRun {
		return fmt.Errorf("one price repeats for %d fixes, a frozen feed rather than a market", run)
	}
	last := pts[len(pts)-1].Date
	if age := now.Sub(last).Hours() / 24; age > maxAge {
		return fmt.Errorf("the last fix %s is %.0f days old, the source has stopped", last.Format(time.DateOnly), age)
	}
	return nil
}
