package main

import (
	"fmt"
	"log"
	"time"

	"github.com/bpineau/pofo/cmd/internal/refgen"
	"github.com/bpineau/pofo/pkg/marketdata"
)

// WTI-USD, the monthly SPOT price this command also refreshes.
//
// It is FRED's WTISPLC, carried exactly as FRED prints it: the month's average
// of the daily West Texas Intermediate spot price, dated the first of the
// month, from 1946-01. It is the deep proxy behind CL=F (simgen's longBack) and
// the FIRE book's commodities plate. It is spot, so it prices no roll: that is
// what WTI-ER-USD, the main series of this command, exists for.
//
// It lives here because it is the other half of the crude-oil family, and it
// had no generator at all until 2026-09: the file froze at 2026-05 with nothing
// to say so.
const (
	outSpot  = "WTI-USD"
	spotFRED = "WTISPLC"

	// spotStart is FRED's first month, and the bundle's.
	spotStart = "1946-01-01"
	// spotFloats is when crude became a traded price: NYMEX listed the WTI
	// contract in 1983, and before 1974 the source is a POSTED price that
	// stood still for years (65 identical months ending 1953-05, 64 ending
	// 1964-06, 18 as late as 1979). From here a repeated month is a frozen
	// feed; measured, no two consecutive months since 1983 print the same
	// value.
	spotFloats = "1986-01-01"
	spotMaxRun = 3
	// spotMaxAge bounds the age of the last label: WTISPLC is dated the first
	// of the month it averages and published early in the next.
	spotMaxAge = 100
	// spotRevisable is how many of the bundled file's last months may be
	// revised by the refresh; EIA does revise its latest spot averages now
	// and then, and anything older moving means the source changed.
	spotRevisable = 3
)

// spotSource is the file's "# source:" header. The measurement of what the
// month-average cadence costs, and why the labels stay on the first, is the
// part a consumer needs.
const spotSource = "WTI spot price (FRED WTISPLC, monthly, 1946->); public domain. Proxy behind CL=F (~2000). " +
	"CADENCE: WTISPLC is the month's AVERAGE of the daily spot prices, dated the first of the month as FRED " +
	"publishes it, so the level is reached mid-month and the monthly returns are smoothed: against the real daily " +
	"spot it stands on (WTI-DAILY, 1986-2000) it reads 0.83 of the daily series' monthly volatility, and its monthly " +
	"returns correlate 0.74 contemporaneously against 0.50 one month late. It stays on the first of the month " +
	"because no label is right for a month-average (month-start and month-end are wrong by the same fifteen days " +
	"in opposite directions) and moving it would slide the whole 1946-2000 reconstruction for nothing; " +
	"simgen.monthEndAnchor deliberately leaves it out, so its anchors pin to the first trading day of the month " +
	"rather than the last. Regenerated by cmd/gen-wti-refdata (make wti-refdata), which carries FRED's values and " +
	"labels unchanged and refuses a refresh that does not reproduce this file's history."

// refreshSpot downloads WTISPLC, checks it against what a crude-oil price must
// look like and against the bundled file in dir, and returns it; nothing is
// written here.
func refreshSpot(base, dir string) ([]marketdata.Point, error) {
	pts, err := refgen.FRED(base, spotFRED)
	if err != nil {
		return nil, err
	}
	log.Printf("%s: %d months, %s to %s", outSpot, len(pts),
		pts[0].Date.Format("2006-01"), pts[len(pts)-1].Date.Format("2006-01"))
	if err := checkSpot(pts); err != nil {
		return nil, err
	}
	old, ok, err := marketdata.ReadSimdata(dir, outSpot)
	if err != nil {
		return nil, fmt.Errorf("reading the bundled file: %w", err)
	}
	if !ok {
		log.Printf("%s: no bundled file in %s to compare with", outSpot, dir)
		return pts, nil
	}
	msg, err := refgen.SameHistory(old.Points, pts, spotRevisable)
	if err != nil {
		return nil, fmt.Errorf("does not reproduce the bundled history: %w", err)
	}
	log.Printf("%s history: %s", outSpot, msg)
	return pts, nil
}

// checkSpot grades the spot series on its own: FRED's first month and layout,
// a plausible price throughout, three eras an outside reader knows (the posted
// prices before the 1973 embargo, the OPEC decade, the 2008 peak), no frozen
// run since crude became a traded price, and a fresh last month.
func checkSpot(pts []marketdata.Point) error {
	if first := pts[0].Date.Format(time.DateOnly); first != spotStart {
		return fmt.Errorf("starts %s, want %s", first, spotStart)
	}
	if err := refgen.MonthlyCadence(pts); err != nil {
		return err
	}
	for _, p := range pts {
		if !(p.Close > 0.5 && p.Close < 300) {
			return fmt.Errorf("%.2f USD a barrel on %s, outside (0.5, 300)", p.Close, p.Date.Format(time.DateOnly))
		}
	}
	for _, e := range []struct {
		what     string
		from, to string
		lo, hi   float64
	}{
		{"the posted-price era", "1946-01-01", "1973-09-01", 1.5, 4.5},
		{"the OPEC decade", "1974-01-01", "1985-12-01", 12, 35},
		{"the 2008 peak", "2008-06-01", "2008-07-01", 120, 145},
	} {
		var sum float64
		var n int
		for _, p := range pts {
			if d := p.Date.Format(time.DateOnly); d >= e.from && d <= e.to {
				sum += p.Close
				n++
			}
		}
		mean := sum / float64(max(n, 1))
		log.Printf("check %s %s: mean %.2f USD over %d months", outSpot, e.what, mean, n)
		if n == 0 || mean < e.lo || mean > e.hi {
			return fmt.Errorf("%s (%s..%s) averages %.2f USD, outside %.1f..%.1f", e.what, e.from, e.to, mean, e.lo, e.hi)
		}
	}
	from, _ := time.Parse(time.DateOnly, spotFloats)
	run, end := refgen.FlatRun(pts, from)
	log.Printf("check %s flat runs since %s: longest %d months (ending %s)", outSpot, spotFloats, run, end.Format("2006-01"))
	if run > spotMaxRun {
		return fmt.Errorf("one value repeats for %d months, a frozen feed rather than a market", run)
	}
	last := pts[len(pts)-1].Date
	if age := time.Since(last).Hours() / 24; age > spotMaxAge {
		return fmt.Errorf("the last month %s is %.0f days old, the source has stopped", last.Format("2006-01"), age)
	}
	return nil
}
